### ISSUE TITLE
 Upgrade to version 0.7.0?

### ISSUE THREAD

**Issue by elcste** [tasdomas/ripgrep-snap#1]
Any chance you can update this to the latest version <strike>[(0.6.0)](https://github.com/BurntSushi/ripgrep/releases/tag/0.6.0)</strike> [(0.7.0)](https://github.com/BurntSushi/ripgrep/releases/tag/0.7.0)?

**Comment by bungcip** [comment]
+1. I also using this snap version of ripgrep on my VPS machine. Would be nice if it updated to latest version.

**Comment by tasdomas** [comment]
@bungcip @elcste - updated.

Sorry about the delay - life got a bit busy, dropped the ball on this one.

**Comment by elcste** [comment]
No worries — life happens.

**Comment by bungcip** [comment]
thanks @tasdomas !
BTW, Any interest to merge your work to to official ripgrep repo? It seem ripgrep already have `snapcraft.yml` (https://github.com/BurntSushi/ripgrep/blob/master/snapcraft.yaml) but still don't have official snap release.
