### ISSUE TITLE
please either fix this package or remove it from snap

### ISSUE THREAD

**Issue by BurntSushi** [tasdomas/ripgrep-snap#2]
According to [this comment](https://github.com/BurntSushi/ripgrep/issues/902#issuecomment-404798881), this package is configured in a way that appears to always cause it to fail.

I don't know much about snap, so I'm filing this issue based on the word of someone else, but I'd appreciate it if this package could either be fixed or removed. I'm asking this because I'm the one who suffers from this broken package in the way of a wave of bug reports.

I would have filed this issue earlier, but @mati865's comment is the only way I was even able to discover that this repo was the ultimate source of the problem because [the snap page](https://snapcraft.io/rg) for this package lists exactly zero details on where to file bugs. (And thus, folks reasonably default to filing bugs against ripgrep.)

Moreover, the snap page for this package lists the license as proprietary, which is grossly incorrect.

**Comment by tasdomas** [comment]
@BurntSushi  - sorry about this, updating the snap build to use classic confinement (should allow access to files outside the user's directory).

**Comment by tasdomas** [comment]
@BurntSushi  - the rg snap will be deprecated in favor of the ripgrep snap (the snapcraft.yaml for which is maintained as part of the ripgrep repo).

**Comment by BurntSushi** [comment]
@tasdomas Great, thank you for the update! Will that deprecation notice be posted anywhere?

**Comment by tasdomas** [comment]
@BurntSushi Yes, the latest version will print out a deprecation warning when used in interactive mode.

**Comment by BurntSushi** [comment]
This still doesn't seem to be fixed. The snap page for rg doesn't indicate that anything is deprecated and it still lists the license as proprietary. Could you please fix this?

**Comment by tasdomas** [comment]
@BurntSushi - the snap has been removed.

**Comment by BurntSushi** [comment]
@tasdomas Thanks! Appreciate it.
